/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@mexample.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@mexample.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringV2 x_p0, void* ClE_0);
void* ClE_0;
} tyProc__yjDZcG8hRpOjknSYmSKIDw;
typedef N_CLOSURE_PTR(NI, TM__DfQaFFoJOv5Rj9bYYIj8A9cg_4) (NimStringV2 x_p0);
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef N_CLOSURE_PTR(NI, TM__DfQaFFoJOv5Rj9bYYIj8A9cg_7) (NimStringV2 x_p0, void* ClE_0);
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
typedef NI tyArray__b2FCGUkcaLn6NMyY7P9aUnw[5];
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
typedef NimStringV2 tyArray__Seu7uK9aaOSN0BK3EAjjSHw[4];
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
static N_INLINE(tySequence__qwqHTkRvwhrRyENtudHQ7g, map__example_u6)(NimStringV2* s_p0, NI s_p0Len_0, tyProc__yjDZcG8hRpOjknSYmSKIDw op_p1);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__example_u16)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw seps_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u318)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___example_u104)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, min__example_u174)(NI* x_p0, NI x_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, sum__example_u186)(NI* x_p0, NI x_p0Len_0);
static N_INLINE(NF, slash___system_u1717)(NI x_p0, NI y_p1);
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__8Np6tlClE5az1CyqZdN19bQ, zip__example_u223)(NI* s1_p0, NI s1_p0Len_0, NI* s2_p1, NI s2_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___example_u321)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, newSeq__example_u449)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___example_u107)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u491)(NimStringV2* result_p0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u497)(NimStringV2* result_p0, NF value_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u544)(NimStringV2* result_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5657)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_3 = { 27 | NIM_STRLIT_FLAG, "Enter counts for A B C D F:" };
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__DfQaFFoJOv5Rj9bYYIj8A9cg_6 = {
0x00, 0x3e, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[150+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_11 = { 150 | NIM_STRLIT_FLAG, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__DfQaFFoJOv5Rj9bYYIj8A9cg_12 = {150, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_11};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_14 = { 9 | NIM_STRLIT_FLAG, "Probation" };
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_15 = { 12 | NIM_STRLIT_FLAG, "Satisfactory" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_16 = { 6 | NIM_STRLIT_FLAG, "Honors" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_17 = { 11 | NIM_STRLIT_FLAG, "High Honors" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_20 = { 10 | NIM_STRLIT_FLAG, "Subjects: " };
static const NimStringV2 TM__DfQaFFoJOv5Rj9bYYIj8A9cg_21 = {10, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_20};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_22 = { 8 | NIM_STRLIT_FLAG, " | GPA: " };
static const NimStringV2 TM__DfQaFFoJOv5Rj9bYYIj8A9cg_23 = {8, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_22};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_24 = { 13 | NIM_STRLIT_FLAG, " | Standing: " };
static const NimStringV2 TM__DfQaFFoJOv5Rj9bYYIj8A9cg_25 = {13, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_24};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__DfQaFFoJOv5Rj9bYYIj8A9cg_27 = { 13 | NIM_STRLIT_FLAG, "\342\235\214 Invalid!\012" };
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__DfQaFFoJOv5Rj9bYYIj8A9cg_2 = {{27, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_3}}
;
static NIM_CONST tyArray__b2FCGUkcaLn6NMyY7P9aUnw TM__DfQaFFoJOv5Rj9bYYIj8A9cg_8 = {((NI)4),
((NI)3),
((NI)2),
((NI)1),
((NI)0)}
;
static NIM_CONST tyArray__Seu7uK9aaOSN0BK3EAjjSHw TM__DfQaFFoJOv5Rj9bYYIj8A9cg_13 = {{9, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_14},
{12, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_15},
{6, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_16},
{11, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_17}}
;
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__DfQaFFoJOv5Rj9bYYIj8A9cg_26 = {{13, (NimStrPayload*)&TM__DfQaFFoJOv5Rj9bYYIj8A9cg_27}}
;
N_LIB_PRIVATE tySequence__qwqHTkRvwhrRyENtudHQ7g c__example_u170;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
N_LIB_PRIVATE NimStringV2 s__example_u474;
N_LIB_PRIVATE NF gpa__example_u473;
N_LIB_PRIVATE tySequence__8Np6tlClE5az1CyqZdN19bQ colontmp___example_u410;
N_LIB_PRIVATE tySequence__qwqHTkRvwhrRyENtudHQ7g resultX60gensym2___example_u458;
N_LIB_PRIVATE NI iX60gensym2___example_u417;
N_LIB_PRIVATE tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ* it__example_u462;
N_LIB_PRIVATE NimStringV2 fmtRes__example_u482;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(tySequence__qwqHTkRvwhrRyENtudHQ7g, map__example_u6)(NimStringV2* s_p0, NI s_p0Len_0, tyProc__yjDZcG8hRpOjknSYmSKIDw op_p1) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g result;
NIM_BOOL* nimErr_;
	nimfr_("map", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");	if ((s_p0Len_0) < ((NI)0) || (s_p0Len_0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0Len_0, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__example_u16((&result), (s_p0Len_0));
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		nimlf_(486, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");		colontmp_ = s_p0Len_0;
		nimlf_(128, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI T4_;
				NI TM__DfQaFFoJOv5Rj9bYYIj8A9cg_5;
				if (!(i_2 < colontmp_)) goto LA3;
				nimlf_(486, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");				i_1 = i_2;
				nimln_(487);				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				T4_ = (NI)0;
				T4_ = op_p1.ClE_0? op_p1.ClP_0(s_p0[i_1], op_p1.ClE_0):((TM__DfQaFFoJOv5Rj9bYYIj8A9cg_4)(op_p1.ClP_0))(s_p0[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[i_1] = T4_;
				nimlf_(131, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__DfQaFFoJOv5Rj9bYYIj8A9cg_5)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_5);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NF, toFloat__system_u1705)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(1314, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, slash___system_u1717)(NI x_p0, NI y_p1) {
	NF result;
	NF T1_;
	NF T2_;
	nimfr_("/", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimln_(1350);	T1_ = (NF)0;
	T1_ = toFloat__system_u1705(x_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1705(y_p1);
	result = ((NF)(T1_) / (NF)(T2_));
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("example", "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");
nimErr_ = nimErrorFlag();
	{
		nimlf_(3, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");		while (1) {
			NimStringV2 colontmpD_;
			tySequence__sM4lkSb7zS6F7OVMvW9cffQ colontmpD__2;
			tyProc__yjDZcG8hRpOjknSYmSKIDw T4_;
			tySequence__qwqHTkRvwhrRyENtudHQ7g T5_;
			c__example_u170.len = 0; c__example_u170.p = NIM_NIL;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(4);			echoBinSafe(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_2, 1);
			nimln_(5);			colontmpD_ = readLine__stdZsyncio_u318(stdin);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			colontmpD__2 = nsuSplitCharSet(colontmpD_, TM__DfQaFFoJOv5Rj9bYYIj8A9cg_6, ((NI)-1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			nimZeroMem((void*)(&T4_), sizeof(tyProc__yjDZcG8hRpOjknSYmSKIDw));
			T4_.ClP_0 = ((TM__DfQaFFoJOv5Rj9bYYIj8A9cg_7) (nsuParseInt)); T4_.ClE_0 = NIM_NIL;
			T5_.len = 0; T5_.p = NIM_NIL;
			T5_ = map__example_u6(((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len, T4_);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___example_u104(T5_); goto LA3_;}
			c__example_u170 = T5_;
			nimln_(6);			{
				NIM_BOOL T8_;
				NIM_BOOL T9_;
				NI T10_;
				NI T12_;
				NI T14_;
				tySequence__qwqHTkRvwhrRyENtudHQ7g colontmpD__3;
				NimStringV2 colontmpD__4;
				tySequence__qwqHTkRvwhrRyENtudHQ7g T18_;
				NI T31_;
				NI T32_;
				NI TM__DfQaFFoJOv5Rj9bYYIj8A9cg_18;
				NI TM__DfQaFFoJOv5Rj9bYYIj8A9cg_19;
				tyArray__YgExxhfgKcesA5EOUj1MOA T33_;
				T8_ = (NIM_BOOL)0;
				T9_ = (NIM_BOOL)0;
				T10_ = c__example_u170.len;
				T9_ = (T10_ == ((NI)5));
				if (!(T9_)) goto LA11_;
				T12_ = (NI)0;
				T12_ = min__example_u174(((c__example_u170).p) ? (c__example_u170.p->data) : NIM_NIL, c__example_u170.len);
				T9_ = (((NI)0) <= T12_);
LA11_: ;
				T8_ = T9_;
				if (!(T8_)) goto LA13_;
				T14_ = (NI)0;
				T14_ = sum__example_u186(((c__example_u170).p) ? (c__example_u170.p->data) : NIM_NIL, c__example_u170.len);
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				T8_ = (((NI)0) < T14_);
LA13_: ;
				if (!T8_) goto LA15_;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				s__example_u474.len = 0; s__example_u474.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				gpa__example_u473 = 0;
				nimln_(7);				T18_.len = 0; T18_.p = NIM_NIL;
				{
					tySequence__8Np6tlClE5az1CyqZdN19bQ T20_;
					NI T21_;
					colontmp___example_u410.len = 0; colontmp___example_u410.p = NIM_NIL;
					resultX60gensym2___example_u458.len = 0; resultX60gensym2___example_u458.p = NIM_NIL;
					nimlf_(112, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");					nimlf_(7, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");					T20_.len = 0; T20_.p = NIM_NIL;
					T20_ = zip__example_u223(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_8, 5, ((c__example_u170).p) ? (c__example_u170.p->data) : NIM_NIL, c__example_u170.len);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___example_u321(T20_); goto LA17_;}
					colontmp___example_u410 = T20_;
					iX60gensym2___example_u417 = 0;
					nimlf_(1107, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");					iX60gensym2___example_u417 = ((NI)0);
					nimln_(1108);					T21_ = colontmp___example_u410.len;
					if ((T21_) < ((NI)0) || (T21_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T21_, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA17_;
					}
					resultX60gensym2___example_u458 = newSeq__example_u449((T21_));
					{
						NI i_1;
						NI L_1;
						NI T23_;
						it__example_u462 = 0;
						nimlf_(249, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");						i_1 = ((NI)0);
						nimln_(250);						T23_ = colontmp___example_u410.len;
						L_1 = T23_;
						{
							nimln_(251);							while (1) {
								NI TM__DfQaFFoJOv5Rj9bYYIj8A9cg_9;
								NI TM__DfQaFFoJOv5Rj9bYYIj8A9cg_10;
								if (!(i_1 < L_1)) goto LA25;
								nimlf_(1109, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");								if (i_1 < 0 || i_1 >= colontmp___example_u410.len){ raiseIndexError2(i_1,colontmp___example_u410.len-1); goto LA17_;
								}
								it__example_u462 = (&colontmp___example_u410.p->data[i_1]);
								nimln_(1110);								if (iX60gensym2___example_u417 < 0 || iX60gensym2___example_u417 >= resultX60gensym2___example_u458.len){ raiseIndexError2(iX60gensym2___example_u417,resultX60gensym2___example_u458.len-1); goto LA17_;
								}
								nimlf_(7, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");								if (nimMulInt((*it__example_u462).Field0, (*it__example_u462).Field1, &TM__DfQaFFoJOv5Rj9bYYIj8A9cg_9)) { raiseOverflow(); goto LA17_;
								};
								resultX60gensym2___example_u458.p->data[iX60gensym2___example_u417] = (NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_9);
								nimlf_(1111, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");								if (nimAddInt(iX60gensym2___example_u417, ((NI)1), &TM__DfQaFFoJOv5Rj9bYYIj8A9cg_10)) { raiseOverflow(); goto LA17_;
								};
								iX60gensym2___example_u417 = (NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_10);
								nimlf_(13, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");								i_1 += ((NI)1);
								nimln_(254);								{
									NI T28_;
									T28_ = colontmp___example_u410.len;
									if (!!((T28_ == L_1))) goto LA29_;
									failedAssertImpl__stdZassertions_u95(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_12);
									if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
								}
LA29_: ;
							} LA25: ;
						}
					}
					nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");					eqcopy___example_u107((&colontmpD__3), resultX60gensym2___example_u458);
					eqdestroy___example_u104(resultX60gensym2___example_u458);
					nimln_(384);					eqdestroy___example_u321(colontmp___example_u410);
					T18_ = colontmpD__3;
				}
				nimlf_(7, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");				T31_ = (NI)0;
				T31_ = sum__example_u186(((T18_).p) ? (T18_.p->data) : NIM_NIL, T18_.len);
				if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				T32_ = (NI)0;
				T32_ = sum__example_u186(((c__example_u170).p) ? (c__example_u170.p->data) : NIM_NIL, c__example_u170.len);
				if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
				gpa__example_u473 = slash___system_u1717(T31_, T32_);
				nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				nimlf_(8, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");				if (nimAddInt(((NI) ((2.0 <= gpa__example_u473))), ((NI) ((3.0 <= gpa__example_u473))), &TM__DfQaFFoJOv5Rj9bYYIj8A9cg_18)) { raiseOverflow(); goto LA17_;
				};
				if (nimAddInt((NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_18), ((NI) ((3.51 <= gpa__example_u473))), &TM__DfQaFFoJOv5Rj9bYYIj8A9cg_19)) { raiseOverflow(); goto LA17_;
				};
				if ((NU)((NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_19)) > (NU)(3)){ raiseIndexError2((NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_19), 3); goto LA17_;
				}
				nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqcopy___system_u2772((&s__example_u474), TM__DfQaFFoJOv5Rj9bYYIj8A9cg_13[((NI)(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_19))- 0]);
				nimlf_(9, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");				{
					NI T35_;
					fmtRes__example_u482.len = 0; fmtRes__example_u482.p = NIM_NIL;
					nimlf_(653, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");					nimlf_(9, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");					fmtRes__example_u482 = rawNewString(((NI)80));
					prepareAdd((&fmtRes__example_u482), 10);
appendString((&fmtRes__example_u482), TM__DfQaFFoJOv5Rj9bYYIj8A9cg_21);
					T35_ = (NI)0;
					T35_ = sum__example_u186(((c__example_u170).p) ? (c__example_u170.p->data) : NIM_NIL, c__example_u170.len);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
					formatValue__example_u491((&fmtRes__example_u482), T35_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
					prepareAdd((&fmtRes__example_u482), 8);
appendString((&fmtRes__example_u482), TM__DfQaFFoJOv5Rj9bYYIj8A9cg_23);
					formatValue__example_u497((&fmtRes__example_u482), gpa__example_u473);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
					prepareAdd((&fmtRes__example_u482), 13);
appendString((&fmtRes__example_u482), TM__DfQaFFoJOv5Rj9bYYIj8A9cg_25);
					formatValue__example_u544((&fmtRes__example_u482), s__example_u474);
					if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
					nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");					eqcopy___system_u2772((&colontmpD__4), fmtRes__example_u482);
					nimln_(394);					if (fmtRes__example_u482.p && !(fmtRes__example_u482.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(fmtRes__example_u482.p);
}
					T33_[0] = colontmpD__4;
				}
				echoBinSafe(T33_, 1);
				if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
				if (s__example_u474.p && !(s__example_u474.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s__example_u474.p);
}
				nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");				eqdestroy___example_u104(colontmpD__3);
				nimlf_(2219, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqdestroy___system_u5657(colontmpD__2);
				nimln_(394);				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");				eqdestroy___example_u104(c__example_u170);
				nimlf_(10, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");				goto LA1;
				{
					LA17_:;
				}
				{
					nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (s__example_u474.p && !(s__example_u474.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s__example_u474.p);
}
					nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");					eqdestroy___example_u104(colontmpD__3);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			}
LA15_: ;
			nimlf_(11, "/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/example.nim");			echoBinSafe(TM__DfQaFFoJOv5Rj9bYYIj8A9cg_26, 1);
			{
				LA3_:;
			}
			{
				nimlf_(2219, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqdestroy___system_u5657(colontmpD__2);
				nimln_(394);				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");				eqdestroy___example_u104(c__example_u170);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	} LA1: ;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

