/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pmath.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pmath.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, sum__example_u186)(NI* x_p0, NI x_p0Len_0) {
	NI result;
	nimfr_("sum", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim");
{	result = (NI)0;
	{
		NI* i_1;
		NI i_2;
		i_1 = (NI*)0;
		nimlf_(18, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(19);			while (1) {
				NI TM__YqBQIdfvZX5pt75kDBsDLg_2;
				if (!(i_2 < x_p0Len_0)) goto LA3;
				nimlf_(1132, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/math.nim");				if (i_2 < 0 || i_2 >= x_p0Len_0){ raiseIndexError2(i_2,x_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = (&x_p0[i_2]);
				if (nimAddInt(result, (*i_1), &TM__YqBQIdfvZX5pt75kDBsDLg_2)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_2);
				nimlf_(13, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
