/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@psequtils.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@psequtils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA {
	NI len;
	void* p;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__example_u236)(tySequence__8Np6tlClE5az1CyqZdN19bQ* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__example_u24)(tySequence__qwqHTkRvwhrRyENtudHQ7g* s_p0, NI newlen_p1);
static N_INLINE(void, nimCopySeqPayload)(void* dest_p0, void* src_p1, NI elemSize_p2, NI elemAlign_p3);
N_LIB_PRIVATE N_NIMCALL(NI, align__system_u1648)(NI address_p0, NI alignment_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___example_u104)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NI));
}
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__8Np6tlClE5az1CyqZdN19bQ, zip__example_u223)(NI* s1_p0, NI s1_p0Len_0, NI* s2_p1, NI s2_p1Len_0) {
	tySequence__8Np6tlClE5az1CyqZdN19bQ result;
	NI mX60gensym11__1;
	nimfr_("zip", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(383, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");	mX60gensym11__1 = ((s1_p0Len_0 <= s2_p1Len_0) ? s1_p0Len_0 : s2_p1Len_0);
	nimln_(384);	if ((mX60gensym11__1) < ((NI)0) || (mX60gensym11__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(mX60gensym11__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__example_u236((&result), (mX60gensym11__1));
	{
		NI iX60gensym11__1;
		NI i_1;
		iX60gensym11__1 = (NI)0;
		nimlf_(128, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		i_1 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI colontmp_;
				NI colontmp__2;
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_2;
				if (!(i_1 < mX60gensym11__1)) goto LA3;
				nimlf_(385, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/collections/sequtils.nim");				iX60gensym11__1 = i_1;
				nimln_(386);				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= s1_p0Len_0){ raiseIndexError2(iX60gensym11__1,s1_p0Len_0-1); goto BeforeRet_;
				}
				colontmp_ = s1_p0[iX60gensym11__1];
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= s2_p1Len_0){ raiseIndexError2(iX60gensym11__1,s2_p1Len_0-1); goto BeforeRet_;
				}
				colontmp__2 = s2_p1[iX60gensym11__1];
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= result.len){ raiseIndexError2(iX60gensym11__1,result.len-1); goto BeforeRet_;
				}
				result.p->data[iX60gensym11__1].Field0 = colontmp_;
				result.p->data[iX60gensym11__1].Field1 = colontmp__2;
				nimlf_(131, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(i_1, ((NI)1), &TM__77ITQxrABVT9b2GcbWeV4SQ_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_2);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___example_u321)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
}
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (x_p0))).p == (*((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (y_p1))).p);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, nimCopySeqPayload)(void* dest_p0, void* src_p1, NI elemSize_p2, NI elemAlign_p3) {
	tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA* d_1;
	tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA* s_1;
{	d_1 = ((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (dest_p0));
	s_1 = ((tyObject_NimRawSeq__2kUMFDNh0hpLnOTOSL0tSA*) (src_p1));
	{
		NI headerSize_1;
		NI TM__77ITQxrABVT9b2GcbWeV4SQ_3;
		if (!(((NI)0) < (*s_1).len)) goto LA3_;
		headerSize_1 = align__system_u1648(((NI)8), elemAlign_p3);
		if (nimMulInt((*s_1).len, elemSize_p2, &TM__77ITQxrABVT9b2GcbWeV4SQ_3)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3)) < ((NI)0) || ((NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1755(((void*) ((NU)((NU64)(((NU) (ptrdiff_t) ((*d_1).p))) + (NU64)(((NU) (headerSize_1)))))), ((void*) ((NU)((NU64)(((NU) (ptrdiff_t) ((*s_1).p))) + (NU64)(((NU) (headerSize_1)))))), ((NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3)));
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___example_u107)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest_p0, tySequence__qwqHTkRvwhrRyENtudHQ7g src_p1) {
	NI T6_;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__example_u24((&(*dest_p0)), T6_);
	nimCopySeqPayload(dest_p0, (&src_p1), ((NI)8), ((NI)8));
	}BeforeRet_: ;
}
