/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstrformat.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstrformat.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw;
typedef struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw;
struct tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw {
	NIM_CHAR fill;
	NIM_CHAR align;
	NIM_CHAR sign;
	NIM_BOOL alternateForm;
	NIM_BOOL padWithZero;
	NI minimumWidth;
	NI precision;
	NIM_CHAR typ;
	NI endPosition;
};
struct tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, formatFloat__example_u507)(NimStringV2* result_p0, NF value_p1, tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw fmode_p2, tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw* spec_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw format_p1, NI precision_p2, NIM_CHAR decimalSep_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, insert__system_u8806)(NimStringV2* x_p0, NimStringV2 item_p1, NI i_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(NimStringV2 s_p0, tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg x_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pureZstrformat_u20)(NimStringV2 s_p0, NI minimumWidth_p1, NIM_CHAR align_p2, NIM_CHAR fill_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2772)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NI, validateUtf8__pureZunicode_u7339)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__pureZunicode_u342)(NIM_CHAR* s_p0, NI s_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NI, runeLen__pureZunicode_u7167)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NIM_CHAR* s_p0, NI s_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_3 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_2};
N_LIB_PRIVATE NIM_CONST tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw spec__example_u505 = {32, 0, 45, NIM_FALSE, NIM_FALSE, ((NI)0), ((NI)2), 102, ((NI)3)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u491)(NimStringV2* result_p0, NI value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(499, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");	colontmpD_ = dollar___systemZdollars_u14(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1319)(NimStringV2 s_p0, tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg x_p1) {
	NimStringV2 result;
	NI a_1;
	NI L_1;
	NI TM__qDXzsifTQdn8ucTam9cFp4w_4;
	NI TM__qDXzsifTQdn8ucTam9cFp4w_5;
	NI TM__qDXzsifTQdn8ucTam9cFp4w_6;
	nimfr_("[]", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/indices.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(83, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/indices.nim");	a_1 = x_p1.a;
	nimln_(84);	nimln_(59);	if (nimSubInt(s_p0.len, x_p1.b, &TM__qDXzsifTQdn8ucTam9cFp4w_4)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4), a_1, &TM__qDXzsifTQdn8ucTam9cFp4w_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_5), ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_6)) { raiseOverflow(); goto BeforeRet_;
	};
	L_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_6);
	nimln_(85);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((L_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__qDXzsifTQdn8ucTam9cFp4w_7;
				NI TM__qDXzsifTQdn8ucTam9cFp4w_8;
				if (!(i_2 < L_1)) goto LA3;
				nimlf_(86, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/indices.nim");				i_1 = i_2;
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (nimAddInt(i_1, a_1, &TM__qDXzsifTQdn8ucTam9cFp4w_7)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_7) < 0 || (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_7) >= s_p0.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_7),s_p0.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = s_p0.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_7)];
				nimlf_(131, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_8)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_8);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg, dotdot___stdZenumutils_u105)(NI a_p0, NI b_p1) {
	tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg result;
	nimfr_("..", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(436, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	popFrame();
}
static N_INLINE(NI, validateUtf8__pureZunicode_u7339)(NimStringV2 s_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("validateUtf8", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1210, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim");	nimln_(25);	if ((s_p0.len-1)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(((NI)0), (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	nimln_(1210);	result = validateUtf8__pureZunicode_u342((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(((NI)0))) : NIM_NIL), ((s_p0.len-1))-(((NI)0))+1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, runeLen__pureZunicode_u7167)(NimStringV2 s_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("runeLen", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1175);	nimln_(25);	if ((s_p0.len-1)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(((NI)0), (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	nimln_(1175);	result = nucruneLen((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(((NI)0))) : NIM_NIL), ((s_p0.len-1))-(((NI)0))+1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pureZstrformat_u20)(NimStringV2 s_p0, NI minimumWidth_p1, NIM_CHAR align_p2, NIM_CHAR fill_p3) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("alignString", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(343, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");	{
		if (!(minimumWidth_p1 == ((NI)0))) goto LA3_;
		nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		eqcopy___system_u2772((&result), s_p0);
	}
	goto LA1_;
LA3_: ;
	{
		NI colontmpD_;
		NI colontmpD__2;
		NI sRuneLen_1;
		NI toFill_1;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_11;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimlf_(346, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");		{
			NI T8_;
			T8_ = (NI)0;
			T8_ = validateUtf8__pureZunicode_u7339(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(T8_ == ((NI)-1))) goto LA9_;
			colontmpD_ = runeLen__pureZunicode_u7167(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			sRuneLen_1 = colontmpD_;
		}
		goto LA6_;
LA9_: ;
		{
			colontmpD__2 = s_p0.len;
			sRuneLen_1 = colontmpD__2;
		}
LA6_: ;
		nimln_(347);		if (nimSubInt(minimumWidth_p1, sRuneLen_1, &TM__qDXzsifTQdn8ucTam9cFp4w_11)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_11);
		nimln_(348);		{
			if (!(toFill_1 <= ((NI)0))) goto LA14_;
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqcopy___system_u2772((&result), s_p0);
		}
		goto LA12_;
LA14_: ;
		{
			NIM_BOOL T17_;
			NimStringV2 colontmpD__3;
			NimStringV2 T21_;
			nimlf_(350, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			T17_ = (NIM_BOOL)0;
			T17_ = ((NU8)(align_p2) == (NU8)(60));
			if (T17_) goto LA18_;
			T17_ = ((NU8)(align_p2) == (NU8)(0));
LA18_: ;
			if (!T17_) goto LA19_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			nimln_(351);			T21_.len = 0; T21_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__3 = nsuRepeatChar(fill_p3, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T21_ = rawNewString(s_p0.len + colontmpD__3.len + 0);
appendString((&T21_), s_p0);
appendString((&T21_), colontmpD__3);
			result = T21_;
			nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		goto LA12_;
LA19_: ;
		{
			NimStringV2 colontmpD__4;
			NimStringV2 colontmpD__5;
			NI half_1;
			NimStringV2 T25_;
			NI TM__qDXzsifTQdn8ucTam9cFp4w_12;
			nimlf_(352, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			if (!((NU8)(align_p2) == (NU8)(94))) goto LA23_;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			nimln_(353);			half_1 = (NI)((toFill_1) / (((NI)2)));
			nimln_(354);			T25_.len = 0; T25_.p = NIM_NIL;
			if ((half_1) < ((NI)0) || (half_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(half_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__4 = nsuRepeatChar(fill_p3, (half_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimSubInt(toFill_1, half_1, &TM__qDXzsifTQdn8ucTam9cFp4w_12)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_12)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_12)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_12), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__5 = nsuRepeatChar(fill_p3, ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_12)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T25_ = rawNewString(colontmpD__4.len + s_p0.len + colontmpD__5.len + 0);
appendString((&T25_), colontmpD__4);
appendString((&T25_), s_p0);
appendString((&T25_), colontmpD__5);
			result = T25_;
			nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
		goto LA12_;
LA23_: ;
		{
			NimStringV2 colontmpD__6;
			NimStringV2 T27_;
			colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
			nimlf_(356, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			T27_.len = 0; T27_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__6 = nsuRepeatChar(fill_p3, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T27_ = rawNewString(colontmpD__6.len + s_p0.len + 0);
appendString((&T27_), colontmpD__6);
appendString((&T27_), s_p0);
			result = T27_;
			nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		}
LA12_: ;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, formatFloat__example_u507)(NimStringV2* result_p0, NF value_p1, tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw fmode_p2, tyObject_StandardFormatSpecifier__Kwo8YZ1j7ydv8meNWdbAvw* spec_p3) {
	NimStringV2 f_1;
	NIM_CHAR colontmpD_;
	NIM_CHAR colontmpD__2;
	NimStringV2 res_1;
	NIM_BOOL sign_1;
	NIM_CHAR align_1;
NIM_BOOL* nimErr_;
	nimfr_("formatFloat", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	f_1.len = 0; f_1.p = NIM_NIL;
	colontmpD_ = (NIM_CHAR)0;
	colontmpD__2 = (NIM_CHAR)0;
	res_1.len = 0; res_1.p = NIM_NIL;
	nimlf_(524, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");	if (((*spec_p3).precision) < ((NI)-1) || ((*spec_p3).precision) > ((NI)32)){ raiseRangeErrorI((*spec_p3).precision, ((NI)-1), ((NI)32)); goto BeforeRet_;
	}
	f_1 = nsuformatBiggestFloat(value_p1, fmode_p2, ((*spec_p3).precision), 46);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(525);	sign_1 = NIM_FALSE;
	nimln_(526);	{
		if (!(0.0 <= value_p1)) goto LA3_;
		nimln_(527);		{
			if (!!(((NU8)((*spec_p3).sign) == (NU8)(45)))) goto LA7_;
			nimln_(528);			sign_1 = NIM_TRUE;
			nimln_(529);			{
				if (!(value_p1 == 0.0)) goto LA11_;
				nimln_(530);				{
					NimStringV2 colontmpD__3;
					if (!(((NF)(1.0) / (NF)(value_p1)) == INF)) goto LA15_;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					nimln_(532);					colontmpD__3 = nimCharToStr((*spec_p3).sign);
					insert__system_u8806((&f_1), colontmpD__3, ((NI)0));
					nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
LA15_: ;
			}
			goto LA9_;
LA11_: ;
			{
				NimStringV2 colontmpD__4;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimlf_(534, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");				colontmpD__4 = nimCharToStr((*spec_p3).sign);
				insert__system_u8806((&f_1), colontmpD__4, ((NI)0));
				nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
			}
LA9_: ;
		}
LA7_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimlf_(536, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");		sign_1 = NIM_TRUE;
	}
LA1_: ;
	nimln_(538);	{
		NimStringV2 signStr_1;
		NI toFill_1;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_9;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_10;
		if (!(*spec_p3).padWithZero) goto LA21_;
		signStr_1.len = 0; signStr_1.p = NIM_NIL;
		nimln_(539);		signStr_1 = TM__qDXzsifTQdn8ucTam9cFp4w_3;
		nimln_(540);		{
			NimStringV2 T27_;
			tyObject_HSlice__gNm3PIFaVREVVU9cuqHQIFg T28_;
			NimStringV2 T29_;
			if (!sign_1) goto LA25_;
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			nimlf_(541, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			if (((NI)0) < 0 || ((NI)0) >= f_1.len){ raiseIndexError2(((NI)0),f_1.len-1); goto BeforeRet_;
			}
			T27_.len = 0; T27_.p = NIM_NIL;
			T27_ = nimCharToStr(f_1.p->data[((NI)0)]);
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqsink___system_u2778((&signStr_1), T27_);
			nimlf_(542, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			T28_ = dotdot___stdZenumutils_u105(((NI)1), ((NI)1));
			T29_.len = 0; T29_.p = NIM_NIL;
			T29_ = X5BX5D___pureZstrutils_u1319(f_1, T28_);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T29_); goto BeforeRet_;}
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqsink___system_u2778((&f_1), T29_);
		}
LA25_: ;
		nimlf_(544, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");		if (nimSubInt((*spec_p3).minimumWidth, f_1.len, &TM__qDXzsifTQdn8ucTam9cFp4w_9)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_9), sign_1, &TM__qDXzsifTQdn8ucTam9cFp4w_10)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_10);
		nimln_(545);		{
			NimStringV2 colontmpD__5;
			NimStringV2 T34_;
			if (!(((NI)0) < toFill_1)) goto LA32_;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			nimlf_(546, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			T34_.len = 0; T34_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__5 = nsuRepeatChar(48, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T34_ = rawNewString(colontmpD__5.len + f_1.len + 0);
appendString((&T34_), colontmpD__5);
appendString((&T34_), f_1);
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqsink___system_u2778((&f_1), T34_);
			nimln_(394);			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		}
LA32_: ;
		nimlf_(547, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");		{
			NimStringV2 T39_;
			if (!sign_1) goto LA37_;
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			nimlf_(548, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");			T39_.len = 0; T39_.p = NIM_NIL;
			T39_ = rawNewString(signStr_1.len + f_1.len + 0);
appendString((&T39_), signStr_1);
appendString((&T39_), f_1);
			nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			eqsink___system_u2778((&f_1), T39_);
		}
LA37_: ;
		nimln_(394);		if (signStr_1.p && !(signStr_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(signStr_1.p);
}
	}
LA21_: ;
	nimlf_(551, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");	{
		if (!((NU8)((*spec_p3).align) == (NU8)(0))) goto LA42_;
		colontmpD_ = 62;
		align_1 = colontmpD_;
	}
	goto LA40_;
LA42_: ;
	{
		colontmpD__2 = (*spec_p3).align;
		align_1 = colontmpD__2;
	}
LA40_: ;
	nimln_(552);	res_1 = alignString__pureZstrformat_u20(f_1, (*spec_p3).minimumWidth, align_1, (*spec_p3).fill);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(553);	{
		NimStringV2 colontmpD__6;
		if (!(((NU8)((*spec_p3).typ)) >= ((NU8)(65)) && ((NU8)((*spec_p3).typ)) <= ((NU8)(90)))) goto LA47_;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		nimln_(554);		colontmpD__6 = nsuToUpperAsciiStr(res_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		prepareAdd((&(*result_p0)), colontmpD__6.len + 0);
appendString((&(*result_p0)), colontmpD__6);
		nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
	}
	goto LA45_;
LA47_: ;
	{
		nimlf_(556, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");		prepareAdd((&(*result_p0)), res_1.len + 0);
appendString((&(*result_p0)), res_1);
	}
LA45_: ;
	nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (res_1.p && !(res_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(res_1.p);
}
	if (f_1.p && !(f_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(f_1.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u497)(NimStringV2* result_p0, NF value_p1) {
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(580, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");	formatFloat__example_u507(result_p0, value_p1, ((tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw)1), (&spec__example_u505));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__example_u544)(NimStringV2* result_p0, NimStringV2 value_p1) {
	NimStringV2 value_2;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	value_2.len = 0; value_2.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(600);	nimln_(601);	value_2 = value_p1;
	nimln_(611);	colontmpD_ = alignString__pureZstrformat_u20(value_2, ((NI)0), 0, 32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
