/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstd@ssyncio.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstd@ssyncio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ {
	tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA Sup;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u9133)(NCSTRING x_p0, NCSTRING y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2775)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__stdZsyncio_u95)(void);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4 = { 7 | NIM_STRLIT_FLAG, "errno: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5 = {7, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6 = { 2 | NIM_STRLIT_FLAG, " `" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = {2, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9 = {1, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8};
extern TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_;
extern TNimTypeV2 NTIv2__dqIledu1UrVKUIOm5tw3rQ_;
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_21 = { 11 | NIM_STRLIT_FLAG, "EOF reached" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_22 = {11, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_21};
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NIM_BOOL, eqeq___system_u9133)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");
	nimlf_(2799, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2800);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2801);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u92)(NimStringV2 msg_p0) {
	NimStringV2 colontmpD_;
	tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* T1_;
	nimfr_("raiseEIO", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) nimNewObj(sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_);
	(*T1_).Sup.Sup.name = "IOError";
	nimlf_(161, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");	nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");	colontmpD_ = eqdup___system_u2775(msg_p0);
	(*T1_).Sup.Sup.message = colontmpD_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimlf_(161, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");	raiseExceptionEx((Exception*)T1_, "IOError", "raiseEIO", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim", 161);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u162)(FILE* f_p0) {
NIM_BOOL* nimErr_;
	nimfr_("checkErr", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(175);	{
		int T3_;
		NimStringV2 msg_1;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T7_;
		NCSTRING T8_;
		T3_ = (int)0;
		T3_ = ferror(f_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		msg_1.len = 0; msg_1.p = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(176);		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u29(errno);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T8_ = (NCSTRING)0;
		T8_ = strerror(errno);
		colontmpD__2 = cstrToNimstr(T8_);
		T7_ = rawNewString(colontmpD_.len + colontmpD__2.len + 10);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5);
appendString((&T7_), colontmpD_);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7);
appendString((&T7_), colontmpD__2);
appendString((&T7_), TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9);
		msg_1 = T7_;
		nimln_(177);		clearerr(f_p0);
		nimln_(178);		raiseEIO__stdZsyncio_u92(msg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		{
			LA6_:;
		}
		{
			nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (msg_1.p && !(msg_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__stdZsyncio_u289)(FILE* f_p0, NimStringV2* line_p1) {
	NIM_BOOL result;
	NI pos_1;
	NI sp_1;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(403, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");	result = NIM_FALSE;
	nimln_(473);	pos_1 = ((NI)0);
	nimln_(476);	sp_1 = (((*line_p1).len >= ((NI)80)) ? (*line_p1).len : ((NI)80));
	nimln_(477);	if ((sp_1) < ((NI)0) || (sp_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(sp_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&(*line_p1)), (sp_1));
	{
		nimln_(479);		while (1) {
			NIM_BOOL fgetsSuccess_1;
			void* m_1;
			NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19;
			NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20;
			{
				NI i_1;
				NI i_2;
				i_1 = (NI)0;
				nimlf_(128, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3;
						if (!(i_2 < sp_1)) goto LA5;
						nimlf_(482, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");						i_1 = i_2;
						if (nimAddInt(pos_1, i_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2),(*line_p1).len-1); goto BeforeRet_;
						}
						nimPrepareStrMutationV2((&(*line_p1)));
						(*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2)] = 10;
						nimlf_(131, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3);
					} LA5: ;
				}
			}
			fgetsSuccess_1 = (NIM_BOOL)0;
			{
				nimlf_(485, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");				while (1) {
					{
						NCSTRING T9_;
						NIM_BOOL T10_;
						nimln_(488);						if (pos_1 < 0 || pos_1 >= (*line_p1).len){ raiseIndexError2(pos_1,(*line_p1).len-1); goto BeforeRet_;
						}
						if ((sp_1) < ((int)(-2147483647 -1)) || (sp_1) > ((int)2147483647)){ raiseRangeErrorI(sp_1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
						}
						T9_ = (NCSTRING)0;
						T9_ = fgets(((NCSTRING) ((&(*line_p1).p->data[pos_1]))), ((int) (sp_1)), f_p0);
						T10_ = (NIM_BOOL)0;
						T10_ = eqeq___system_u9133(T9_, ((NCSTRING) NIM_NIL));
						fgetsSuccess_1 = !(T10_);
						nimln_(489);						{
							if (!fgetsSuccess_1) goto LA13_;
							goto LA6;
						}
LA13_: ;
						nimln_(491);						{
							if (!(errno == EINTR)) goto LA17_;
							nimln_(492);							errno = ((int)0);
							nimln_(493);							clearerr(f_p0);
							nimln_(494);							goto LA8;
						}
LA17_: ;
						nimln_(495);						checkErr__stdZsyncio_u162(f_p0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimln_(496);						goto LA6;
					} LA8: ;
				}
			} LA6: ;
			nimln_(498);			if (pos_1 < 0 || pos_1 >= (*line_p1).len){ raiseIndexError2(pos_1,(*line_p1).len-1); goto BeforeRet_;
			}
			m_1 = memchr(((void*) ((&(*line_p1).p->data[pos_1]))), ((int)10), ((size_t) (sp_1)));
			nimln_(499);			{
				NI last_1;
				NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10;
				NIM_BOOL T42_;
				if (!!((m_1 == NIM_NIL))) goto LA21_;
				nimln_(501);				if (((NI)0) < 0 || ((NI)0) >= (*line_p1).len){ raiseIndexError2(((NI)0),(*line_p1).len-1); goto BeforeRet_;
				}
				if (nimSubInt(((NI) (ptrdiff_t) (m_1)), ((NI) (ptrdiff_t) ((&(*line_p1).p->data[((NI)0)]))), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10)) { raiseOverflow(); goto BeforeRet_;
				};
				last_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10);
				nimln_(502);				{
					NIM_BOOL T25_;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12;
					NIM_BOOL T29_;
					T25_ = (NIM_BOOL)0;
					T25_ = (((NI)0) < last_1);
					if (!(T25_)) goto LA26_;
					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11),(*line_p1).len-1); goto BeforeRet_;
					}
					T25_ = ((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11)]) == (NU8)(13));
LA26_: ;
					if (!T25_) goto LA27_;
					nimln_(503);					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12)) { raiseOverflow(); goto BeforeRet_;
					};
					if (((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12)) < ((NI)0) || ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
					}
					setLengthStrV2((&(*line_p1)), ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12)));
					nimln_(504);					nimln_(395);					nimln_(504);					T29_ = (NIM_BOOL)0;
					T29_ = (((NI)1) < last_1);
					if (T29_) goto LA30_;
					T29_ = fgetsSuccess_1;
LA30_: ;
					result = T29_;
					goto BeforeRet_;
				}
				goto LA23_;
LA27_: ;
				{
					NIM_BOOL T32_;
					NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13;
					nimln_(505);					T32_ = (NIM_BOOL)0;
					T32_ = (((NI)0) < last_1);
					if (!(T32_)) goto LA33_;
					if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13),(*line_p1).len-1); goto BeforeRet_;
					}
					T32_ = ((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13)]) == (NU8)(0));
LA33_: ;
					if (!T32_) goto LA34_;
					nimln_(510);					{
						NIM_BOOL T38_;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16;
						NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17;
						T38_ = (NIM_BOOL)0;
						if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14)) { raiseOverflow(); goto BeforeRet_;
						};
						if (nimSubInt((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_14), ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15)) { raiseOverflow(); goto BeforeRet_;
						};
						T38_ = ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_15) <= last_1);
						if (T38_) goto LA39_;
						if (nimAddInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16) < 0 || (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16) >= (*line_p1).len){ raiseIndexError2((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16),(*line_p1).len-1); goto BeforeRet_;
						}
						T38_ = !(((NU8)((*line_p1).p->data[(NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_16)]) == (NU8)(0)));
LA39_: ;
						if (!T38_) goto LA40_;
						nimln_(511);						if (nimSubInt(last_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17)) { raiseOverflow(); goto BeforeRet_;
						};
						last_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_17);
					}
LA40_: ;
				}
				goto LA23_;
LA34_: ;
LA23_: ;
				nimln_(512);				if ((last_1) < ((NI)0) || (last_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(last_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				setLengthStrV2((&(*line_p1)), (last_1));
				nimln_(513);				nimln_(395);				nimln_(513);				T42_ = (NIM_BOOL)0;
				T42_ = (((NI)0) < last_1);
				if (T42_) goto LA43_;
				T42_ = fgetsSuccess_1;
LA43_: ;
				result = T42_;
				goto BeforeRet_;
			}
			goto LA19_;
LA21_: ;
			{
				NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18;
				nimln_(516);				if (nimSubInt(sp_1, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18)) { raiseOverflow(); goto BeforeRet_;
				};
				sp_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_18);
			}
LA19_: ;
			nimln_(518);			if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19)) { raiseOverflow(); goto BeforeRet_;
			};
			pos_1 = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_19);
			nimln_(519);			sp_1 = ((NI)128);
			nimln_(520);			if (nimAddInt(pos_1, sp_1, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20)) < ((NI)0) || ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			setLengthStrV2((&(*line_p1)), ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_20)));
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEOF__stdZsyncio_u95)(void) {
	tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ* T1_;
	nimfr_("raiseEOF", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ*) nimNewObj(sizeof(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ), NIM_ALIGNOF(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__dqIledu1UrVKUIOm5tw3rQ_);
	(*T1_).Sup.Sup.Sup.name = "EOFError";
	(*T1_).Sup.Sup.Sup.message = TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_22;
	(*T1_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimln_(164);	raiseExceptionEx((Exception*)T1_, "EOFError", "raiseEOF", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim", 164);
goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u318)(FILE* f_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("readLine", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/std/syncio.nim");
{nimErr_ = nimErrorFlag();
	nimln_(526);	result = rawNewString(((NI)80));
	nimln_(527);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = readLine__stdZsyncio_u289(f_p0, (&result));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		raiseEOF__stdZsyncio_u95();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
