/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstrutils.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@pstrutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
typedef NU8 tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw;
typedef NIM_CHAR tyArray__Dz6OE1kpzz8bnx9batFy1Cw[6];
typedef NIM_CHAR tyArray__WALV5e0ysjOIjCclEgOBNg[2501];
typedef NIM_CHAR tyArray__Js6XEvpP0CCIujotSuxUrA[3];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2778)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u9181)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2769)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u981)(NimStringV2 s_p0, NI* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2511)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0);
extern TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_;
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_6 = { 17 | NIM_STRLIT_FLAG, "invalid integer: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_6};
N_LIB_PRIVATE NIM_CONST tyArray__Js6XEvpP0CCIujotSuxUrA floatFormatToChar__pureZstrutils_u2259 = {103,
102,
101}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw seps_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("split", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(418, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym68__1;
		NI lastX60gensym37__1;
		NI splitsX60gensym37__1;
		xX60gensym68__1.len = 0; xX60gensym68__1.p = NIM_NIL;
		nimln_(390);		lastX60gensym37__1 = ((NI)0);
		nimln_(391);		splitsX60gensym37__1 = maxsplit_p2;
		{
			nimln_(507);			while (1) {
				NI firstX60gensym37__1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
				NimStringV2 T13_;
				NimStringV2 blitTmp_1;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
				nimln_(393);				if (!(lastX60gensym37__1 <= s_p0.len)) goto LA4;
				nimln_(394);				firstX60gensym37__1 = lastX60gensym37__1;
				{
					nimln_(395);					while (1) {
						NIM_BOOL T7_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
						T7_ = (NIM_BOOL)0;
						T7_ = (lastX60gensym37__1 < s_p0.len);
						if (!(T7_)) goto LA8_;
						if (lastX60gensym37__1 < 0 || lastX60gensym37__1 >= s_p0.len){ raiseIndexError2(lastX60gensym37__1,s_p0.len-1); goto LA2_;
						}
						T7_ = !(((seps_p1[(NU)((((NU8)(s_p0.p->data[lastX60gensym37__1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[lastX60gensym37__1]))))&7U)))!=0));
LA8_: ;
						if (!T7_) goto LA6;
						nimln_(396);						if (nimAddInt(lastX60gensym37__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto LA2_;
						};
						lastX60gensym37__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
					} LA6: ;
				}
				nimln_(397);				{
					if (!(splitsX60gensym37__1 == ((NI)0))) goto LA11_;
					lastX60gensym37__1 = s_p0.len;
				}
LA11_: ;
				nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				nimlf_(779, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				nimln_(398);				if (nimSubInt(lastX60gensym37__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); goto LA2_;
				};
				nimln_(779);				T13_.len = 0; T13_.p = NIM_NIL;
				T13_ = substr__system_u9181(s_p0, firstX60gensym37__1, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3));
				nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqsink___system_u2778((&xX60gensym68__1), T13_);
				nimlf_(419, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				blitTmp_1 = xX60gensym68__1;
				nimlf_(1715, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");				eqwasMoved___system_u2769((&xX60gensym68__1));
				nimlf_(419, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				add__stdZenumutils_u70((&result), blitTmp_1);
				nimln_(399);				{
					if (!(splitsX60gensym37__1 == ((NI)0))) goto LA16_;
					goto LA3;
				}
LA16_: ;
				nimln_(400);				if (nimSubInt(splitsX60gensym37__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); goto LA2_;
				};
				splitsX60gensym37__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4);
				nimln_(401);				if (nimAddInt(lastX60gensym37__1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto LA2_;
				};
				lastX60gensym37__1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
			} LA4: ;
		} LA3: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system.nim");			if (xX60gensym68__1.p && !(xX60gensym68__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(xX60gensym68__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringV2 s_p0) {
	NI result;
	NI L_1;
NIM_BOOL* nimErr_;
	nimfr_("parseInt", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(1157, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");	result = ((NI)0);
	nimln_(1158);	L_1 = parseInt__pureZparseutils_u981(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1159);	{
		NIM_BOOL T3_;
		tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) nimNewObj(sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__NZcE89crkraWmH1VkcjYX9ag_);
		(*T7_).Sup.Sup.name = "ValueError";
		nimln_(1160);		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseInt", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim", 1160);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2511(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuformatBiggestFloat)(NF f_p0, tyEnum_FloatFormatMode__zwHPAp79cDfFY4N9bMFVg2Bw format_p1, NI precision_p2, NIM_CHAR decimalSep_p3) {
	NimStringV2 result;
	tyArray__Dz6OE1kpzz8bnx9batFy1Cw frmtstr_1;
	tyArray__WALV5e0ysjOIjCclEgOBNg buf_1;
	int L_1;
	nimfr_("formatBiggestFloat", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	L_1 = (int)0;
	nimln_(2554);	frmtstr_1[(((NI)0))- 0] = 37;
	nimln_(2555);	{
		if (!(((NI)0) <= precision_p2)) goto LA3_;
		nimln_(2556);		frmtstr_1[(((NI)1))- 0] = 35;
		nimln_(2557);		frmtstr_1[(((NI)2))- 0] = 46;
		nimln_(2558);		frmtstr_1[(((NI)3))- 0] = 42;
		nimln_(2559);		frmtstr_1[(((NI)4))- 0] = floatFormatToChar__pureZstrutils_u2259[(format_p1)- 0];
		nimln_(2560);		frmtstr_1[(((NI)5))- 0] = 0;
		nimln_(2561);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), precision_p2, f_p0);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(2563);		frmtstr_1[(((NI)1))- 0] = floatFormatToChar__pureZstrutils_u2259[(format_p1)- 0];
		nimln_(2564);		frmtstr_1[(((NI)2))- 0] = 0;
		nimln_(2565);		L_1 = snprintf(((NCSTRING) (buf_1)), ((size_t)2501), ((NCSTRING) (frmtstr_1)), f_p0);
	}
LA1_: ;
	nimln_(2566);	if ((L_1) < ((NI)0) || (L_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString(((NI) (L_1)));
	{
		NI32 i_1;
		NI32 res_1;
		i_1 = (NI32)0;
		nimlf_(137, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI32)0);
		{
			nimln_(138);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
				if (!(res_1 < L_1)) goto LA8;
				nimlf_(2567, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				i_1 = res_1;
				nimln_(2570);				{
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					if (!(((NU8)(buf_1[(i_1)- 0])) == ((NU8)(46)) || ((NU8)(buf_1[(i_1)- 0])) == ((NU8)(44)))) goto LA11_;
					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					result.p->data[i_1] = decimalSep_p3;
				}
				goto LA9_;
LA11_: ;
				{
					nimln_(2571);					if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
					}
					nimPrepareStrMutationV2((&result));
					if ((NU)(i_1) > (NU)(2500)){ raiseIndexError2(i_1, 2500); goto BeforeRet_;
					}
					result.p->data[i_1] = buf_1[(i_1)- 0];
				}
LA9_: ;
				nimlf_(140, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); goto BeforeRet_;
				};
				if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 < (-2147483647 -1) || TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 > 2147483647){ raiseOverflow(); goto BeforeRet_;
				}
				res_1 = (NI32)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
	nimfr_("repeat", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
{	nimlf_(1351, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");	result = mnewString(count_p1);
	{
		NI i_1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		nimlf_(1352, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");		if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
		nimlf_(96, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(1352, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				i_1 = ((NI) (res_1));
				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				result.p->data[i_1] = c_p0;
				nimlf_(102, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nsuToUpperAsciiChar)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	nimfr_("toUpperAscii", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
	nimlf_(255, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");	{
		if (!(((NU8)(c_p0)) >= ((NU8)(97)) && ((NU8)(c_p0)) <= ((NU8)(122)))) goto LA3_;
		nimln_(256);		result = ((NIM_CHAR) ((NU8)(((NU8) (((NU8)(c_p0)))) ^ ((NU8)32))));
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(258);		result = c_p0;
	}
LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuToUpperAsciiStr)(NimStringV2 s_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toUpperAscii", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(224);	if ((s_p0.len) < ((NI)0) || (s_p0.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(s_p0.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((s_p0.len));
	{
		NI iX60gensym11__1;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
		NI res_1;
		iX60gensym11__1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(81, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		nimlf_(225, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");		if (nimSubInt(s_p0.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
		nimlf_(96, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(97);			while (1) {
				NIM_CHAR T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
				if (!(res_1 <= colontmp_)) goto LA3;
				nimlf_(271, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/pure/strutils.nim");				iX60gensym11__1 = ((NI) (res_1));
				nimln_(226);				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= result.len){ raiseIndexError2(iX60gensym11__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				if (iX60gensym11__1 < 0 || iX60gensym11__1 >= s_p0.len){ raiseIndexError2(iX60gensym11__1,s_p0.len-1); goto BeforeRet_;
				}
				T4_ = (NIM_CHAR)0;
				T4_ = nsuToUpperAsciiChar(s_p0.p->data[iX60gensym11__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				result.p->data[iX60gensym11__1] = T4_;
				nimlf_(102, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
