/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib -I/home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205 -o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@psystem@sexceptions.nim.c.o /home/narayanas/Documents/BCA/bcapdf/bca-pdf-hub-main/assignment/pdfs/2nd_Semester/MCSL-205/nim_csource_code/@psystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw;
typedef struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg;
typedef struct tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w;
typedef struct tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw;
typedef struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA tySequence__UIJx6FJrflnhA9a3u1VF1vA;
typedef struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content;
typedef struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q;
typedef struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g;
typedef struct tyTuple__WEETd9ajw9a010wvV0CoGNuw tyTuple__WEETd9ajw9a010wvV0CoGNuw;
typedef struct tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg;
typedef struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA;
typedef struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag;
typedef struct tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ;
typedef struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag;
typedef struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw;
typedef struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA {
  NI len; tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__UIJx6FJrflnhA9a3u1VF1vA trace;
	Exception* up;
};
struct tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w {
	tyObject_ArithmeticDefect__aOZfpsWsYxgjFBl3u6zGIw Sup;
};
struct tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g {
	NI len;
	NI cap;
	tyTuple__WEETd9ajw9a010wvV0CoGNuw* d;
};
struct tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q {
	tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g traceStack;
	tyObject_CellSeq__bUU9cGCnoYZUQbR5GgWvc0g toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag {
	Exception Sup;
};
struct tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ {
	tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA Sup;
};
struct tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag {
	tyObject_CatchableError__kvV4Jp5z2ULaSZq53myi9ag Sup;
};
struct tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw {
	tyObject_Defect__9cay1P9cMS9bqQj8GzEyUp67g Sup;
};
struct tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__UIJx6FJrflnhA9a3u1VF1vA_Content { NI cap; tyObject_StackTraceEntry__UznwMnjUHK6AxZHnP9bMXEA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4641)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4511)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3573)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5114)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3775)(tySequence__UIJx6FJrflnhA9a3u1VF1vA dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5126)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3102)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4653)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4710)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4722)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9255)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9267)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZsyncio_u100)(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZsyncio_u112)(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__39bmND756Jn4TbmMyoPiAaw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__CGiRGxBaa9ayq9c0XyRtJx1w_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bd1PhiEWFQ1CQmRpNFMavg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__dqIledu1UrVKUIOm5tw3rQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__fAtMgIeNQyfDKIqRjGsXPw_;
extern NIM_THREADVAR TFrame* framePtr__system_u2809;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4293;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 2897559296, 3865028096, 1754340096};
N_LIB_PRIVATE TNimTypeV2 NTIv2__CGiRGxBaa9ayq9c0XyRtJx1w_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_u5126, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 2897559296, 3918335744};
N_LIB_PRIVATE TNimTypeV2 NTIv2__39bmND756Jn4TbmMyoPiAaw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4653, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 2897559296, 3712976384};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9bd1PhiEWFQ1CQmRpNFMavg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___system_u4722, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 4118291968, 376841216};
N_LIB_PRIVATE TNimTypeV2 NTIv2__DxZ2JM72pLUaxjq9asr9aWqA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), .align = (NI16) NIM_ALIGNOF(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___system_u9267, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[5] = {3701606400, 1285336064, 4118291968, 376841216, 2720364800};
N_LIB_PRIVATE TNimTypeV2 NTIv2__dqIledu1UrVKUIOm5tw3rQ_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u66, .size = sizeof(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ), .align = (NI16) NIM_ALIGNOF(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_6, .traceImpl = (void*)eqtrace___stdZsyncio_u112, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 4118291968, 2533683968};
N_LIB_PRIVATE TNimTypeV2 NTIv2__NZcE89crkraWmH1VkcjYX9ag_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u68, .size = sizeof(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___pureZparseutils_u342, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 2897559296, 189562880};
N_LIB_PRIVATE TNimTypeV2 NTIv2__fAtMgIeNQyfDKIqRjGsXPw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u70, .size = sizeof(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw), .align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_8, .traceImpl = (void*)eqtrace___stdZassertions_u49, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2809 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2809).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2809;
	framePtr__system_u2809 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4511();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2809 = (*framePtr__system_u2809).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimlf_(377, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5114)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4293);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5114(((tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/arithmetics.nim");
	nimln_(366);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3094)(tyObject_CellSeq__tmpRNCI2baMQRvZpqUI72g* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3102(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimlf_(138, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__85WwC9a1qDcL9aPJ9b1qr0g2Q*) (env_p1));
		nimln_(141);		add__system_u3094((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5126)(tyObject_OverflowDefect__CGiRGxBaa9ayq9c0XyRtJx1w* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__sqhyc4FSbGmPtkvXRNl9acg*) (T5_));
		nimlf_(521, "/home/narayanas/.choosenim/toolchains/nim-2.2.10/lib/system/orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3573(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4641)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4641(((tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4653)(tyObject_RangeDefect__39bmND756Jn4TbmMyoPiAaw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4710)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4710(((tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4722)(tyObject_IndexDefect__9bd1PhiEWFQ1CQmRpNFMavg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u9255)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u9255(((tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u9267)(tyObject_IOError__DxZ2JM72pLUaxjq9asr9aWqA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZsyncio_u100)(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZsyncio_u100(((tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZsyncio_u112)(tyObject_EOFError__dqIledu1UrVKUIOm5tw3rQ* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZparseutils_u330(((tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__NZcE89crkraWmH1VkcjYX9ag* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u37)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3775((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___stdZassertions_u37(((tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_u49)(tyObject_AssertionDefect__fAtMgIeNQyfDKIqRjGsXPw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
